version: '3.8'
services:
    api:
        container_name: product-api
        image: products-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 80:80
        depends_on:
            postgres:
                condition: service_healthy